[package]
name = "bert"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
metal = ["candle-token-classification/metal"]

[dependencies]
anyhow = "1.0"
candle-core.workspace = true
candle-nn.workspace = true
candle-token-classification = { path = "../.." }
candle-transformers.workspace = true
clap = { version = "4.2.4", features = ["derive"] }
hf-hub = "0.3.0"
itertools = "0.12"
safetensors = "0.3"
serde.workspace = true
serde_json.workspace = true
tokenizers.workspace = true
tracing = "0.1.37"
tracing-chrome = "0.7.1"
tracing-subscriber = "0.3.7"
